# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: valuePlaceHolder # from-param: ${job-name}
  labels:
    cloud.googleapis.com/location: northamerica-northeast1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: valuePlaceHolder # from-param: ${cloudsql-instances}
    spec:
      taskCount: 1 # from-param: ${task-count}
      template:
        spec:
          containers:
          - image: image-placeholder
            command:
            - valuePlaceHolder # from-param: ${run-command}
            env:
            - name: DEPLOYMENT_PLATFORM
              value: GCP
            - name: DEPLOYMENT_ENV
              value: development # from-param: ${deploy-env}
            - name: DEPLOYMENT_PROJECT
              value: xxxxxx-dev # from-param: ${deploy-project-id}
            resources:
              limits:
                cpu: 1000m # from-param: ${resources-cpu}
              memory: 512Mi # from-param: ${resources-memory}
            maxRetries: 3 # from-param: ${task-max-retries}
            timeoutSeconds: 600 # from-param: ${task-timeout}
            serviceAccountName: valuePlaceHolder # from-param: ${service-account}