# Default values for bcregistry-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: "dev"
role: "api"

image:
  repository: "image-registry.openshift-image-registry.svc:5000"
  namespace: "d893f6-tools"
  pullPolicy: "IfNotPresent"
  pullSecrets: ""
  digest: ""
  tag: "dev"

migrations:
  enabled: false

ports:
  containerPort: 8080
  protocol: TCP

resources: {wwwwwww}

replicas: 1

revisionHistoryLimit: 10

livenessProbe:
  httpGet:
    path: /api/v1/ops/healthz
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/ops/readyz
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  timeoutSeconds: 30
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

args: {}

env:
  {}
  # SOME_ENV_VAR:
  #   value: "var2"
  #   secure: false
  # SOME_SEC_ENV_VAR:
  #   value: "var"
  #   secure: true

envFrom:
  secretRef: true
  configMapRef: false

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

route:
  create: true
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # haproxy.router.openshift.io/ip_whitelist: ''
    # haproxy.router.openshift.io/timeout: 900s
  routerCanonicalHostname: apps.silver.devops.gov.bc.ca
  path: ""
  service: {}
  wildcardPolicy: None
  tls: {}

autoscaling:
  # Specifies whether the autoscaling should be created
  create: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""