name: Notify API CD OCP

on:
  push:
    branches:
      - main
    paths:
      - "notify-api/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  notify-api-cd:
    uses: pwei1018/bcregistry-sre/.github/workflows/backend-cd-ocp.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "notify-api"
      working_directory: "./notify-api"
    secrets:
      OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_URL }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_DOCKER_REGISTRY }}
      OPENSHIFT_LOGIN_REGISTRY: ${{secrets.OPENSHIFT_LOGIN_REGISTRY}}
      OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME }}
      OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
      OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}
