name: Notify API CI

on:
  pull_request:
    paths:
      - "notify-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./notify-api

jobs:
  notify-api-ci:
    uses: pwei1018/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "notify-api"
      working_directory: "./notify-api"
      codecov_flag: "notifyapi"